name: Despicaleaderboards
author: Despical
version: ${project.version}
api-version: 1.13
main: me.despical.leaderboards.Main
depend: [ PlaceholderAPI ]
softdepend: [ KOTL, OITC, TNTRun, WhackMe, MurderMystery ]